version: '3.8'


services:
  app:
    image: nvcr.io/nvidia/pytorch:23.10-py3
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '256M'
    depends_on:
      - db
  db:
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hamdi
      POSTGRES_DB: mydatabase
volumes:
  postgres-data: